# Generated by Django 4.2.2 on 2023-06-16 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filesupload',
            old_name='file2',
            new_name='file',
        ),
    ]
