# Generated by Django 4.2.2 on 2023-06-25 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0002_rename_file2_filesupload_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success_count', models.IntegerField()),
                ('results_count', models.IntegerField()),
                ('files_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileupload.filesupload')),
            ],
        ),
    ]
