# Generated by Django 4.2.2 on 2023-06-25 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0003_processedresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedresult',
            name='file',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
